<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegistroVolumetricoSeeder extends Seeder
{
    public function run(): void
    {
        $today = Carbon::today();
        $ayer = Carbon::yesterday();
        $hace2 = Carbon::today()->subDays(2);
        $hace3 = Carbon::today()->subDays(3);
        $hace5 = Carbon::today()->subDays(5);

        $registros = [
            [
                'numero_registro' => 'RV-'.$today->format('Ymd').'-001',
                'instalacion_id' => 1,
                'tanque_id' => 1,
                'medidor_id' => 1,
                'producto_id' => 1,
                'usuario_registro_id' => 1,
                'usuario_valida_id' => 1,
                'fecha' => $today->toDateString(),
                'hora_inicio' => '06:00:00',
                'hora_fin' => '06:30:00',
                'volumen_inicial' => 3000.0000,
                'volumen_final' => 5000.0000,
                'volumen_operacion' => 2000.0000,
                'temperatura_inicial' => 18.50,
                'temperatura_final' => 19.00,
                'presion_inicial' => 1.013,
                'presion_final' => 1.013,
                'densidad' => 0.7400,
                'volumen_corregido' => 1960.0000,
                'factor_correccion' => 0.980000,
                'detalle_correccion' => json_encode(['metodo' => 'tabla_aforo']),
                'masa' => 1450.4000,
                'tipo_registro' => 'operacion',
                'operacion' => 'recepcion',
                'estado' => 'VALIDADO',
                'fecha_validacion' => $today->toDateString().' 07:00:00',
                'observaciones' => 'Recepción de gasolina regular',
                'created_at' => $today,
                'updated_at' => $today,
            ],
            [
                'numero_registro' => 'RV-'.$today->format('Ymd').'-002',
                'instalacion_id' => 1,
                'tanque_id' => 1,
                'medidor_id' => 1,
                'producto_id' => 1,
                'usuario_registro_id' => 1,
                'usuario_valida_id' => null,
                'fecha' => $today->toDateString(),
                'hora_inicio' => '10:00:00',
                'hora_fin' => '10:15:00',
                'volumen_inicial' => 5000.0000,
                'volumen_final' => 4200.0000,
                'volumen_operacion' => 800.0000,
                'temperatura_inicial' => 19.00,
                'temperatura_final' => 19.50,
                'presion_inicial' => 1.013,
                'presion_final' => 1.013,
                'densidad' => 0.7400,
                'volumen_corregido' => 784.0000,
                'factor_correccion' => 0.980000,
                'detalle_correccion' => json_encode(['metodo' => 'tabla_aforo']),
                'masa' => 592.0000,
                'tipo_registro' => 'operacion',
                'operacion' => 'entrega',
                'estado' => 'PENDIENTE',
                'observaciones' => 'Entrega a dispensario',
                'created_at' => $today,
                'updated_at' => $today,
            ],
            [
                'numero_registro' => 'RV-'.$ayer->format('Ymd').'-001',
                'instalacion_id' => 1,
                'tanque_id' => 2,
                'medidor_id' => 2,
                'producto_id' => 2,
                'usuario_registro_id' => 1,
                'usuario_valida_id' => 1,
                'fecha' => $ayer->toDateString(),
                'hora_inicio' => '08:00:00',
                'hora_fin' => '08:20:00',
                'volumen_inicial' => 2000.0000,
                'volumen_final' => 4500.0000,
                'volumen_operacion' => 2500.0000,
                'temperatura_inicial' => 20.00,
                'temperatura_final' => 20.50,
                'presion_inicial' => 1.013,
                'presion_final' => 1.013,
                'densidad' => 0.7600,
                'volumen_corregido' => 2450.0000,
                'factor_correccion' => 0.980000,
                'detalle_correccion' => json_encode(['metodo' => 'tabla_aforo']),
                'masa' => 1900.0000,
                'tipo_registro' => 'operacion',
                'operacion' => 'recepcion',
                'estado' => 'VALIDADO',
                'fecha_validacion' => $ayer->toDateString().' 09:00:00',
                'observaciones' => 'Recepción de gasolina premium',
                'created_at' => $ayer,
                'updated_at' => $ayer,
            ],
            [
                'numero_registro' => 'RV-'.$ayer->format('Ymd').'-002',
                'instalacion_id' => 1,
                'tanque_id' => 3,
                'medidor_id' => 3,
                'producto_id' => 3,
                'usuario_registro_id' => 1,
                'usuario_valida_id' => null,
                'fecha' => $ayer->toDateString(),
                'hora_inicio' => '14:00:00',
                'hora_fin' => '14:30:00',
                'volumen_inicial' => 12000.0000,
                'volumen_final' => 10500.0000,
                'volumen_operacion' => 1500.0000,
                'temperatura_inicial' => 22.00,
                'temperatura_final' => 22.50,
                'presion_inicial' => 1.013,
                'presion_final' => 1.013,
                'densidad' => 0.8400,
                'volumen_corregido' => 1485.0000,
                'factor_correccion' => 0.990000,
                'detalle_correccion' => json_encode(['metodo' => 'tabla_aforo']),
                'masa' => 1260.0000,
                'tipo_registro' => 'operacion',
                'operacion' => 'venta',
                'estado' => 'PENDIENTE',
                'observaciones' => 'Venta de diesel',
                'created_at' => $ayer,
                'updated_at' => $ayer,
            ],
            [
                'numero_registro' => 'RV-'.$hace2->format('Ymd').'-001',
                'instalacion_id' => 1,
                'tanque_id' => 1,
                'medidor_id' => 1,
                'producto_id' => 1,
                'usuario_registro_id' => 1,
                'usuario_valida_id' => 1,
                'fecha' => $hace2->toDateString(),
                'hora_inicio' => '07:00:00',
                'hora_fin' => '07:30:00',
                'volumen_inicial' => 1000.0000,
                'volumen_final' => 3500.0000,
                'volumen_operacion' => 2500.0000,
                'temperatura_inicial' => 18.00,
                'temperatura_final' => 18.50,
                'presion_inicial' => 1.013,
                'presion_final' => 1.013,
                'densidad' => 0.7400,
                'volumen_corregido' => 2450.0000,
                'factor_correccion' => 0.980000,
                'detalle_correccion' => json_encode(['metodo' => 'tabla_aforo']),
                'masa' => 1850.0000,
                'tipo_registro' => 'operacion',
                'operacion' => 'recepcion',
                'estado' => 'VALIDADO',
                'fecha_validacion' => $hace2->toDateString().' 08:00:00',
                'observaciones' => 'Recepción programada',
                'created_at' => $hace2,
                'updated_at' => $hace2,
            ],
            [
                'numero_registro' => 'RV-'.$hace3->format('Ymd').'-001',
                'instalacion_id' => 1,
                'tanque_id' => 2,
                'medidor_id' => 2,
                'producto_id' => 2,
                'usuario_registro_id' => 1,
                'usuario_valida_id' => null,
                'fecha' => $hace3->toDateString(),
                'hora_inicio' => '12:00:00',
                'hora_fin' => '12:20:00',
                'volumen_inicial' => 6000.0000,
                'volumen_final' => 5000.0000,
                'volumen_operacion' => 1000.0000,
                'temperatura_inicial' => 21.00,
                'temperatura_final' => 21.50,
                'presion_inicial' => 1.013,
                'presion_final' => 1.013,
                'densidad' => 0.7600,
                'volumen_corregido' => 980.0000,
                'factor_correccion' => 0.980000,
                'detalle_correccion' => json_encode(['metodo' => 'tabla_aforo']),
                'masa' => 760.0000,
                'tipo_registro' => 'operacion',
                'operacion' => 'entrega',
                'estado' => 'VALIDADO',
                'fecha_validacion' => $hace3->toDateString().' 13:00:00',
                'observaciones' => 'Entrega a dispensario premium',
                'created_at' => $hace3,
                'updated_at' => $hace3,
            ],
            [
                'numero_registro' => 'RV-'.$hace5->format('Ymd').'-001',
                'instalacion_id' => 1,
                'tanque_id' => 3,
                'medidor_id' => 3,
                'producto_id' => 3,
                'usuario_registro_id' => 1,
                'usuario_valida_id' => 1,
                'fecha' => $hace5->toDateString(),
                'hora_inicio' => '09:00:00',
                'hora_fin' => '09:45:00',
                'volumen_inicial' => 8000.0000,
                'volumen_final' => 15000.0000,
                'volumen_operacion' => 7000.0000,
                'temperatura_inicial' => 20.00,
                'temperatura_final' => 20.50,
                'presion_inicial' => 1.013,
                'presion_final' => 1.013,
                'densidad' => 0.8400,
                'volumen_corregido' => 6930.0000,
                'factor_correccion' => 0.990000,
                'detalle_correccion' => json_encode(['metodo' => 'tabla_aforo']),
                'masa' => 5880.0000,
                'tipo_registro' => 'operacion',
                'operacion' => 'recepcion',
                'estado' => 'VALIDADO',
                'fecha_validacion' => $hace5->toDateString().' 10:00:00',
                'observaciones' => 'Recepción masiva de diesel',
                'created_at' => $hace5,
                'updated_at' => $hace5,
            ],
        ];

        foreach ($registros as $registro) {
            DB::table('registros_volumetricos')->insert($registro);
        }
    }
}
